name: search_reddit
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.1.1
  loading_overlay: ^0.3.0
  get_it: ^7.2.0
  http: ^0.13.5
  fluttertoast: ^8.1.1
  firebase_crashlytics: ^3.0.6
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  google_sign_in: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0  
  build_runner: ^2.2.0
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/png/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
